package com.example.feature_single_course.constant

import androidx.compose.ui.unit.dp

object CourseInfoViewConstant {
    val COURSE_INFO_IMAGE_SIZE = 250.dp
    val COURSE_INFO_IMAGE_BUTTON_PADDING=16.dp
    val COURSE_INFO_IMAGE_BUTTON_ICON_SIZE=44.dp
    val COURSE_INFO_IMAGE_BUTTON_ICON_CLIP=28.dp
    val COURSE_INFO_IMAGE_BUTTON_ICON_OFFSET=1.dp
    val COURSE_INFO_IMAGE_INFO_BOX_PADDING = 8.dp
    val COURSE_INFO_IMAGE_INFO_BOX_ICON_STAR_SIZE = 12.dp
    val COURSE_INFO_IMAGE_INFO_BOX_SPACER = 4.dp
    val COURSE_INFO_PADDING = 16.dp
    val COURSE_INFO_TEXT_SPACER = 16.dp
    val COURSE_INFO_AVTOR_LOGO_SIZE = 40.dp
    val COURSE_INFO_AVTOR_LOGO_CLIP = 20.dp
    val COURSE_INFO_AVTOR_TEXT_SPACER = 12.dp
    val COURSE_INFO_AVTOR_TO_BUTTON_SPACER= 32.dp
    val COURSE_INFO_BUTTON_TO_BUTTON_SPACER= 8.dp
    val COURSE_INFO_BUTTON_HEIGHT= 40.dp
    val COURSE_INFO_BUTTON_TEXT_FONT_SIZE= 14
    val COURSE_INFO_BUTTON_TO_COURSE_INFO_LABEL_SPACER= 28.dp
    val COURSE_INFO_COURSE_INFO_LABEL_TO_INFO_SPACER= 12.dp
    val COURSE_INFO_DESCRIPTION_TEXT_FONT_SIZE= 14
    val COURSE_INFO_DESCRIPTION_TEXT_LINE_HEIGHT= 20
    val COURSE_INFO_DESCRIPTION_TEXT_LETTERSPACING= 0.25


}